import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const slug = process.argv[2];
const model = process.env.DEEPINFRA_MODEL || "deepseek-ai/DeepSeek-V3";
const apiKey = process.env.DEEPINFRA_API_KEY;

if (!slug || !/^[a-z0-9-]+$/.test(slug)) {
  console.error("Usage: npm run draft:review -- <slug>");
  process.exit(1);
}

if (!apiKey) {
  console.error("Missing DEEPINFRA_API_KEY. Add it to .env.local; never commit that file.");
  process.exit(1);
}

const evidencePath = path.join(root, "research", slug, "evidence.json");
const briefPath = path.join(root, "research", "ARTICLE_BRIEF.md");
const queuePath = path.join(root, "research", "queue.json");

for (const requiredPath of [evidencePath, briefPath, queuePath]) {
  if (!fs.existsSync(requiredPath)) {
    console.error(`Required drafting input is missing: ${path.relative(root, requiredPath)}`);
    process.exit(1);
  }
}

const evidence = JSON.parse(fs.readFileSync(evidencePath, "utf8"));
const queue = JSON.parse(fs.readFileSync(queuePath, "utf8"));
const queueItem = queue.find((item) => item.slug === slug);
const brief = fs.readFileSync(briefPath, "utf8");

if (!queueItem) {
  console.error(`${slug} is not in research/queue.json.`);
  process.exit(1);
}
if (evidence.productSlug !== slug) {
  console.error("Evidence productSlug does not match the requested slug.");
  process.exit(1);
}
if (!Array.isArray(evidence.sources) || evidence.sources.length < 6) {
  console.error("Drafting is blocked until the evidence packet has at least six sources.");
  process.exit(1);
}
if (!Array.isArray(evidence.claims) || evidence.claims.length < 3) {
  console.error("Drafting is blocked until the evidence packet has at least three documented claims.");
  process.exit(1);
}
if (!evidence.releaseDate?.date || !evidence.releaseDate?.sourceId) {
  console.error("Drafting is blocked until the evidence packet has a verified release date.");
  process.exit(1);
}

const systemPrompt = `You are the first-draft writer for Digital Macaroni, an independent software review publication. You write only from the supplied evidence packet and editorial brief. Facts must come only from claims marked verified or supported and their named sources. Do not add prices, features, outcomes, customer stories, or testing details. Do not claim hands-on use unless evidence.testing.accessedProduct is true. Never copy source wording. If evidence is uncertain, state the uncertainty plainly. Take a direct editorial stance supported by the score rationale. Return Markdown article body only: no frontmatter, no prefacing note, no source list, and no citations. Do not use em dashes or en dashes.`;

const userPrompt = `Write a 700 to 1,000 word first draft for ${queueItem.product}, a ${queueItem.category} product. Follow this editorial brief exactly:\n\n${brief}\n\nEvidence packet (the release date is private and must never appear in the article):\n\n${JSON.stringify(evidence, null, 2)}`;

const response = await fetch("https://api.deepinfra.com/v1/openai/chat/completions", {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
    Authorization: `Bearer ${apiKey}`,
  },
  body: JSON.stringify({
    model,
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt },
    ],
    temperature: 0.45,
    max_tokens: 2_200,
  }),
});

const payload = await response.json().catch(() => null);
if (!response.ok) {
  const detail = payload?.error?.message || payload?.detail || response.statusText;
  console.error(`DeepInfra request failed (${response.status}): ${detail}`);
  process.exit(1);
}

const draft = payload?.choices?.[0]?.message?.content?.trim();
if (!draft) {
  console.error("DeepInfra returned no draft text.");
  process.exit(1);
}

const draftDirectory = path.join(root, "research", slug, "drafts");
fs.mkdirSync(draftDirectory, { recursive: true });
const createdAt = new Date().toISOString();
const filename = `${createdAt.replace(/[:.]/g, "-")}-deepinfra.md`;
const outputPath = path.join(draftDirectory, filename);
const header = `<!--\nDraft only. Generated by ${model} through DeepInfra on ${createdAt}.\nUse as an editorial starting point. Verify every claim against research/${slug}/evidence.json before moving text into content/reviews/${slug}.mdx.\n-->\n\n`;
fs.writeFileSync(outputPath, `${header}${draft}\n`);

const usage = payload.usage;
console.log(`First draft saved to ${path.relative(root, outputPath)}.`);
if (usage) console.log(`Usage: ${usage.prompt_tokens ?? "?"} prompt tokens, ${usage.completion_tokens ?? "?"} completion tokens.`);
